name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [windows, macos]
        include:
          - name: windows
            os: windows-latest
            artifact_name: target/release/postgres-typescript-generator.exe
            asset_name: postgres-typescript-generator-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/postgres-typescript-generator
            asset_name: postgres-typescript-generator-macos

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}
